config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index', campaign: nil, userid: nil, mw: nil
  get 'pages/index/:user/:mw' => 'pages#index', user: :user, mw: :mw
  post 'crowdsourceuser' => 'users#crowdsourceuser'
  get 'newuser' => 'users#new'
  post 'newuser' => 'users#create'
  get 'about' => 'pages#about'

  get 'intro_part1' => 'pages#intro_part1'
  get 'totraining_part1' => 'pages#totraining_part1'
  get 'training_part1' => 'pages#training_part1'
  get 'golden' => 'pages#golden'
  get 'submit_golden' => 'pages#submit_golden'

  get 'ready_part1' => 'pages#ready_part1'
  get 'show_part1' => 'scores#show_part1'
  get 'checkimage_part1' => 'scores#checkimage_part1'
  get 'contentcheck_part1' => 'scores#contentcheck_part1'

  get 'intro_part2' => 'pages#intro_part2'
  get 'totraining_part2' => 'pages#totraining_part2'
  get 'training_part2' => 'pages#training_part2'

  get 'ready_part2' => 'pages#ready_part2'
  get 'show_part2' => 'scores#show_part2'
  get 'checkimage_part2' => 'scores#checkimage_part2'
  get 'contentcheck_part2' => 'scores#contentcheck_part2'

  post 'update' => 'users#update'
  get 'content' => 'users#content'
  get 'contentanswer' => 'users#contentanswer'

  get 'end' => 'pages#end'
  get 'endwrong' => 'pages#endwrong'
  get 'logout' => 'pages#logout'

  resources :scores

  resources :users

  resources :campaignsets

  resources :images

end

app/models/score.rb
class Score < ActiveRecord::Base
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def show_part1
    @title = "Task - Part 1"
    if session[:checkimage]==1
        @score = Score.new

        #get a golden image
        @golden_question = GoldenQuestion.find(session[:goldens][(session[:golden_num].to_i)])
        @imgid = @golden_question.img_id
        @options = @golden_question.options
        @img = Image.find(@imgid)
        session[:golden_num] = session[:golden_num].to_i + 1
        if(session[:golden_num] > session[:goldens].length-1)
            session[:golden_num] = 0
        end
        @log_code = "1|"+@golden_question.img_id.to_s+"|"+session[:userid].to_s;
    elsif session[:img_num].to_i < session[:images].length
      @score = Score.new
      #set image to be shown
      @img = Image.find((session[:images][(session[:img_num].to_i)].to_i))
      @imgid = (session[:images][(session[:img_num].to_i)].to_i);
      @log_code = "1|"+@imgid.to_s+"|"+session[:userid].to_s;
    else
       redirect_to intro_part2_path
    end 
  end

  def show_part2
      @title = "Task - Part 2"
      if session[:loc_num].to_i < session[:locs].length
        @score = Score.new
        #set image to be shown
        @loc_id = session[:locs][(session[:loc_num].to_i)].to_i
        @imgs = Image.where(loc_id: @loc_id).ids
        @img1 = Image.find(@imgs[0])
        @img2 = Image.find(@imgs[1])
        @img3 = Image.find(@imgs[2])
        @img4 = Image.find(@imgs[3])
        @log_code = "2|"+@loc_id.to_s+"|"+session[:userid].to_s;
      else
         redirect_to end_path
      end
    end

  def create
  #save score value to database
    if session[:checkimage]==1
      #save answer of golden question

    end

    @score = Score.new(score_params)
    @score.end_time = Time.now.strftime("%H:%M:%S %z")
    if @score.save
        if session[:part] == 1
          if session[:img_num].to_i < session[:images].length
              redirect_to checkimage_part1_path
          else
              redirect_to intro_part2_path
          end
        else
          if session[:loc_num].to_i < session[:locs].length
              session[:loc_num] = session[:loc_num].to_i + 1 #increment loc id
              redirect_to show_part2_path
          else
              redirect_to end_path
          end
        end
    else
        if session[:part] == 1
            render '/show_part1'
        else
            render '/show_part2'
        end
    end
  end

  def contentcheck_part1
    session[:img_num] = session[:img_num].to_i + 1 #increment image id
    if session[:checkimage] == 1
          redirect_to show_part1_path
    else
        if session[:img_num].to_i < session[:images].length
          redirect_to show_part1_path
        else
          redirect_to intro_part2_path
        end 
      end 
  end

  def checkimage_part1
      if session[:checkimage] == 1
         session[:img_num] = session[:img_num].to_i - 1 #backtrack
         session[:checkimage] = 0
      else
          if ((session[:img_num]).to_i == 10) || ((session[:img_num]).to_i == 20) || ((session[:img_num]).to_i == 40) || ((session[:img_num]).to_i == 60) || ((session[:img_num]).to_i == 70)
               session[:checkimage] = 1
          else
               session[:checkimage] = 0
          end
      end
      redirect_to contentcheck_part1_path
  end

  def contentcheck_part2
    session[:loc_num] = session[:loc_num].to_i + 1 #increment image id
    if session[:checkloc] == 1
          redirect_to golden_path
    else
        if session[:loc_num].to_i < session[:locs].length
          redirect_to show_part2_path
        else
          redirect_to end_path
        end
      end
  end

  def checkimage_part2
      if ((session[:loc_num]).to_i == 10) || ((session[:loc_num]).to_i == 20) || ((session[:loc_num]).to_i == 40) || ((session[:loc_num]).to_i == 50) || ((session[:loc_num]).to_i == 70)
          session[:checkloc] = 1
      else
          session[:checkloc] = 0 
      end
      redirect_to contentcheck_part2_path
  end


private

  def score_params
    params.require(:score).permit(:user_id, :part, :loc_id, :img_id, :attractiveness, :familiarity, :uniqueness, :friendliness, :pleasure, :arousal, :dominance, :golden_answer, :start_time)
  end

  def golden_params
    params.require()
  end

end

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<% form_for(@score) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :img_id %><br />
    <%= f.text_field :img_id %>
  </p>
  <p>
    <%= f.label :scale %><br />
    <%= f.text_field :scale %>
  </p>
  <p>
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table>
  <tr>
    <th>User</th>
    <th>Img</th>
    <th>Scale</th>
    <th>Score</th>
  </tr>

<% @scores.each do |score| %>
  <tr>
    <td><%=h score.user_id %></td>
    <td><%=h score.img_id %></td>
    <td><%=h score.scale %></td>
    <td><%=h score.score %></td>
    <td><%= link_to 'Show', score %></td>
    <td><%= link_to 'Edit', edit_score_path(score) %></td>
    <td><%= link_to 'Destroy', score, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New score', new_score_path %>

app/views/scores/new.html.erb
<div id="test_image">
<%= link_to image_tag(@img.filepath), '#' %>
</div>

<%= form_for(@score) do |f| %>
  <%= f.hidden_field :score, :id => "amount" %>
  <%= f.hidden_field :recognizability, :id => "amount-Rec" %>
  <%= f.hidden_field :img_id, :value => session[:images][(session[:img_num].to_i)].to_i %>
  <%= f.hidden_field :user_id, :value => session[:userid].to_s %>

	<%= f.hidden_field :scale, :value => session[:scale].to_s %>
	<%= render 'layouts/scaleACR' %>

<div class="buttons"><%= f.submit "Next", class: "btn btn-large btn-primary" %></div>

<% end %>

app/views/scores/show.html.erb
<p>
    #Images = <%=h @score.lgt%>
</p>

<p>
  <b>User:</b>
  <%=h @score.user_id %>
</p>

<p>
  <b>Img:</b>
  <%=h @score.img_id %>
</p>

<p>
  <b>Scale:</b>
  <%=h @score.scale %>
</p>

<p>
  <b>Score:</b>
  <%=h @score.score %>
</p>


<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>

app/views/scores/show_part1.html.erb
<div id="test_image">
<%= link_to image_tag(@img.filepath), '#' %>
</div>

<%= form_for(@score) do |f| %>
  <%= f.hidden_field :attractiveness, :id => "attractiveness" %>
  <%= f.hidden_field :uniqueness, :id => "uniqueness" %>
  <%= f.hidden_field :familiarity, :id => "familiarity" %>
  <%= f.hidden_field :friendliness, :id => "friendliness" %>
  <%= f.hidden_field :start_time, :id => "start_time" %>

  <%= f.hidden_field :part, :id => "part" %>
  <%= f.hidden_field :img_id, :value => @imgid %>
  <%= f.hidden_field :user_id, :value => session[:userid].to_s %>
  <%= f.hidden_field :golden_answer, :id => "golden_answer" %>

  <%= f.hidden_field :pleasure, :id => "pleasure" %>
  <%= f.hidden_field :arousal, :id => "arousal" %>
  <%= f.hidden_field :dominance, :id => "dominance" %>

	<%= render 'layouts/question' %>

<input id="checkimage" value="<%= session[:checkimage] %>" type="hidden" />
<input id="options" value="<%= @options %>" type="hidden" />
<input id="log_code" value="<%= @log_code %>" type="hidden" />

<div id="golden_q" hidden></div>
<div class="buttons" id="next_btn" hidden><%= f.submit "Next", class: "btn btn-large btn-primary" %></div>

<% end %>
<%= javascript_include_tag "external/logger" %>

app/views/scores/show_part2.html.erb
<% if session[:part]==1%>
    <% controller.redirect_to show_part1_path %>
<% end %>

<div id="test_image" class="container">
    <div class="row">
        <%= link_to image_tag(@img1.filepath,class:'col-sm-3',style: 'width:24%;height:auto;'), '#' %>
        <%= link_to image_tag(@img2.filepath,class:'col-sm-3',style: 'width:24%;height:auto;'), '#' %>
        <%= link_to image_tag(@img3.filepath,class:'col-sm-3',style: 'width:24%;height:auto;'), '#' %>
        <%= link_to image_tag(@img4.filepath,class:'col-sm-3',style: 'width:24%;height:auto;'), '#' %>
    </div>
</div>

<%= form_for(@score) do |f| %>
  <%= f.hidden_field :attractiveness, :id => "attractiveness" %>
  <%= f.hidden_field :uniqueness, :id => "uniqueness" %>
  <%= f.hidden_field :familiarity, :id => "familiarity" %>
  <%= f.hidden_field :friendliness, :id => "friendliness" %>
  <%= f.hidden_field :start_time, :id => "start_time" %>

  <%= f.hidden_field :part, :value => 2 %>
  <%= f.hidden_field :loc_id, :value => session[:locs][(session[:loc_num].to_i)].to_i %>
  <%= f.hidden_field :user_id, :value => session[:userid].to_s %>

  <%= f.hidden_field :pleasure, :id => "pleasure" %>
  <%= f.hidden_field :arousal, :id => "arousal" %>
  <%= f.hidden_field :dominance, :id => "dominance" %>

	<%= render 'layouts/question' %>

<input id="log_code" value="<%= @log_code %>" type="hidden" />

<div class="buttons" id="next_btn" hidden><%= f.submit "Next", class: "btn btn-large btn-primary" %></div>

<% end %>

<%= javascript_include_tag "external/logger" %>