config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index', campaign: nil, userid: nil, mw: nil
  get 'pages/index/:user/:mw' => 'pages#index', user: :user, mw: :mw
  post 'crowdsourceuser' => 'users#crowdsourceuser'
  get 'newuser' => 'users#new'
  post 'newuser' => 'users#create'
  get 'about' => 'pages#about'

  get 'intro_part1' => 'pages#intro_part1'
  get 'totraining_part1' => 'pages#totraining_part1'
  get 'training_part1' => 'pages#training_part1'
  get 'golden' => 'pages#golden'
  get 'submit_golden' => 'pages#submit_golden'

  get 'ready_part1' => 'pages#ready_part1'
  get 'show_part1' => 'scores#show_part1'
  get 'checkimage_part1' => 'scores#checkimage_part1'
  get 'contentcheck_part1' => 'scores#contentcheck_part1'

  get 'intro_part2' => 'pages#intro_part2'
  get 'totraining_part2' => 'pages#totraining_part2'
  get 'training_part2' => 'pages#training_part2'

  get 'ready_part2' => 'pages#ready_part2'
  get 'show_part2' => 'scores#show_part2'
  get 'checkimage_part2' => 'scores#checkimage_part2'
  get 'contentcheck_part2' => 'scores#contentcheck_part2'

  post 'update' => 'users#update'
  get 'content' => 'users#content'
  get 'contentanswer' => 'users#contentanswer'

  get 'end' => 'pages#end'
  get 'endwrong' => 'pages#endwrong'
  get 'logout' => 'pages#logout'

  resources :scores

  resources :users

  resources :campaignsets

  resources :images

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/views/users/content.html.erb
	
		<% if (session[:img_num]).to_i == 5 %>
			<div id="test_image">
			<%= link_to image_tag('zebras.jpg'), '#' %>
			</div>
		<% elsif (session[:img_num]).to_i == 19 %>
			<div id="test_image">
			<%= link_to image_tag('car.jpg'), '#' %>
			</div>	
		<% end %>

		<%= render 'layouts/scaleACR' %>
        
		<div class="buttons">
			<%= link_to "Next", contentanswer_path, class: "btn btn-large btn-primary" %> 
		</div>
		
	
		
	

app/views/users/contentanswer.html.erb
<br>
<p>Please answer the following question correctly!</p>
<div class="row">
	<div class="span8 offset2">
		<div class="contentquestion">
		<%= form_tag update_path, :method => :post do %>
		<% if (session[:img_num]).to_i == 5 %>
			<p>What was the main object of the last picture?</p>
			<table align="center" class="question">
			<tr><td><%= radio_button_tag(:answer, "car") %></td>
			<td><%= label_tag(:answer_car, " a car in a desert") %></td></tr>
			<tr><td><%= radio_button_tag(:answer, "eating") %></td>
			<td><%= label_tag(:answer_eating, " man eating fries") %></td></tr>
			<tr><td><%= radio_button_tag(:answer, "zebras") %></td>
			<td><%= label_tag(:answer_zebras, " two zebras in a field") %></td></tr>
			<tr><td><%= radio_button_tag(:answer, "eye") %></td>
			<td><%= label_tag(:answer_eye, " an eye") %></td></tr>
			</table>
		<% elsif (session[:img_num]).to_i == 19 %>
			<p>What was the main object of the last picture?</p>		
			<table align="center" class="question">
			<tr><td><%= radio_button_tag(:answer, "dog") %></td>
			<td><%= label_tag(:answer_dog, " a dog lying down") %></td></tr>
			<tr><td><%= radio_button_tag(:answer, "car") %></td>
			<td><%= label_tag(:answer_car, " a parked car") %></td></tr>
			<tr><td><%= radio_button_tag(:answer, "cake") %></td>
			<td><%= label_tag(:answer_cake, " a cake on display") %></td></tr>
			<tr><td><%= radio_button_tag(:answer, "beach") %></td>
			<td><%= label_tag(:answer_beach, " a beach") %></td></tr>
			</table>
		<% end %>

        
		<div class="buttons">
			<%= submit_tag "Next", class: "btn btn-large btn-primary" %> 
		</div>
		<% end %>
	
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<% form_for(@user) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </p>
  <p>
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Gender</th>
    <th>Age</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%=h user.name %></td>
    <td><%=h user.email %></td>
    <td><%=h user.gender %></td>
    <td><%=h user.age %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<div class="center hero-unit"> 
  <h1>Welcome to the Urban Attractiveness Evaluation Survey</h1>
</div>

<h3>This task is for non-profit research purposes.</h3>
<h3>Tell us which places are attractive!</h3>

<br>

<div class="row">
  <div class="box">
  <div class="span8 offset2">

    <p>Please fill out the details below, and press 'Save and continue' to start the task.</p>

      <%= form_for(@user) do |f| %>
        <%= f.hidden_field :id, :value => session[:userid] %>
        <%= f.hidden_field :start_time, :value => Time.now.strftime("%I:%M:%S %z") %>

        <%= f.label :name %>
        <%= f.text_field :name, :size => '60' %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :gender %>
        <%= f.select :gender, options_for_select(['M', 'F', 'N/A'])%>

        <%= f.label :age %>
        <%= f.select :age, (17..50) %>

        <%= f.label :nationality %>
        <%= f.select :nationality, @nationalities %>

        <%= f.label "Questions Set" %>
        <%= f.select :campaign_id, options_for_select([1,2,3,4,5,6,7,8,9,10]) %>

        <br>
        <br>
        <div class='center'>
        <%= f.submit "Save and continue", class: "btn btn-large btn-primary" %>
        </div>
      <% end %>
   </div>

</div>
</div>

app/views/users/show.html.erb
<p>
  <b>Name:</b>
  <%=h @user.name %>
</p>

<p>
  <b>Email:</b>
  <%=h @user.email %>
</p>

<p>
  <b>Gender:</b>
  <%=h @user.gender %>
</p>

<p>
  <b>Age:</b>
  <%=h @user.age %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>