config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index', campaign: nil, userid: nil, mw: nil
  get 'pages/index/:user/:mw' => 'pages#index', user: :user, mw: :mw
  post 'crowdsourceuser' => 'users#crowdsourceuser'
  get 'newuser' => 'users#new'
  post 'newuser' => 'users#create'
  get 'about' => 'pages#about'

  get 'intro_part1' => 'pages#intro_part1'
  get 'totraining_part1' => 'pages#totraining_part1'
  get 'training_part1' => 'pages#training_part1'
  get 'golden' => 'pages#golden'
  get 'submit_golden' => 'pages#submit_golden'

  get 'ready_part1' => 'pages#ready_part1'
  get 'show_part1' => 'scores#show_part1'
  get 'checkimage_part1' => 'scores#checkimage_part1'
  get 'contentcheck_part1' => 'scores#contentcheck_part1'

  get 'intro_part2' => 'pages#intro_part2'
  get 'totraining_part2' => 'pages#totraining_part2'
  get 'training_part2' => 'pages#training_part2'

  get 'ready_part2' => 'pages#ready_part2'
  get 'show_part2' => 'scores#show_part2'
  get 'checkimage_part2' => 'scores#checkimage_part2'
  get 'contentcheck_part2' => 'scores#contentcheck_part2'

  post 'update' => 'users#update'
  get 'content' => 'users#content'
  get 'contentanswer' => 'users#contentanswer'

  get 'end' => 'pages#end'
  get 'endwrong' => 'pages#endwrong'
  get 'logout' => 'pages#logout'

  resources :scores

  resources :users

  resources :campaignsets

  resources :images

end

app/views/pages/about.html.erb
    <h1>About Us</h1> 
    <p> 
      This test is created for the purpose of non-profit research at the <a href="http://wis.ewi.tudelft.nl/" target="_blank">Web Information System</a> group, TU Delft.
    </p> 

app/views/pages/end.html.erb
<h1>Image Rating Test</h1>

<p>You have reached the end of the task. Thank you for taking part in the test!</p>


<div class="buttons">
  <%= link_to "Back to Home", logout_path, class: "btn btn-large btn-primary" %>
</div>

<p>
<% if session[:vcode].nil? %>
	
<% else %>
	<%= "Your code : " + session[:vcode] %>
<% end %>
</p>

app/views/pages/help.html.erb
    <h1>Help</h1> 


	<p></p>

app/views/pages/index.html.erb
<div class="center hero-unit"> 
  <h1>Urban Attractivness Evaluation</h1>
</div>

<h3>Help us rate the attractiveness of the location shown in each image!</h3>
<h3>This test is for non-profit research purposes.</h3>


<p align="center">Please fill in your gender and age below, for demographic survey in our research only.</p>

<%= form_for User.new, url: crowdsourceuser_path do |f| %>
<%= f.hidden_field(:id, :value => session[:userid].to_s) %>
<table align="center" class="question">
	<tr><td><%= label_tag ("Gender :") %>
	<%= f.select(:gender,options_for_select(["M", "F"])) %></td></tr>

	<tr><td><%= label_tag ("Age :") %>
	<%= f.select(:age,options_for_select((17..50).step(1)))%></td></tr>

	<tr><td><%= label_tag ("Nationality :") %>
    <%= f.select(:nationality,options_for_select(session[:nationalities]))%></td></tr>

</table>
	<div class="buttons">
  	<%= f.submit "Click to continue", class: "btn btn-large btn-primary" %> 
	</div>
<% end %>

app/views/pages/intro.html.erb
<h1>Instructions</h1> 

<% if session[:scale] == 1 %>
	<%= render 'layouts/introACR' %>
<% elsif session[:scale] == 2 %>	
	<%= render 'layouts/introVA' %>
<% elsif session[:scale] == 3 %>
	<%= render 'layouts/introCONT' %>
<% elsif session[:scale] == 4 %>
	<%= render 'layouts/introBIN' %>
<% elsif session[:scale] == 5 %>
	<%= render 'layouts/intro7pt' %>
<% end %>



<div id="wait-text"></div>
<div class="buttons">
  <%= link_to "Start now!", totraining_path, class: "btn btn-large btn-primary", :id => "start-button"%> 
</div>

app/views/pages/intro0.html.erb
<% provide(:title, 'Introduction') %>

<h1>Introduction</h1>

<p>Thank you for participating in this experiment! In this experiment, we ask you to rate several images based on their <b>beauty</b>. Before continuing with the experiment, please make sure that you have signed the consent form.</p>

<ul>
	<li>In this experiment, you will be asked to perform four small tasks of rating images based on their beauty, with a five-minute break after the second task.</li>
	<li>In the beginning of each task, you will be given a set of instructions on how to rate the images.</li>
	<li>After reading the instructions, you will be asked to rate two images as a training on how to rate the images.</li>
	<li>The training is to help you get used to the rating interface. We will not collect data from the training.</li>
	<li>After completing the training, you will then be able to begin the task.</li>
	<li>At the end of each task, please wait for the experimenter to help you start with the next task.</li>
	<li>During the whole experiment, you are allowed to take a break at any moment if you feel tired.</li>
	<li>If you find yourself making a mistake when giving your rating, please inform the experimenter before you rate the next image. The experimenter will write down your correction for the previous' image rating.</li>	
</ul>

<div class="buttons">
  <%= link_to "Click to continue", 'instructions', class: "btn btn-large btn-primary" %> 
</div>

app/views/pages/intro_part2.html.erb
<h1>Instructions - Part 2</h1>

<ul class="instructions-text">
    <li>This task is still similar to the previous task.</li>
    <li>Instead of evaluating 1 image, <b>you will be given 4 images</b> representing views of a single place from 4 different directions in clockwise direction.</li>
    <li>Please answer the questions by selecting the appropriate options.</li>
    <li>After answering the questions in a page, click 'Next' to continue with the next set of images.</li>
</ul>

<p><em>Please note that <b>there is no right or wrong answer</b>.</em></p>



<div id="wait-text"></div>
<div class="buttons">
  <%= link_to "OK, I get it", ready_part2_path, class: "btn btn-large btn-primary", :id => "start-button"%>
</div>

app/views/pages/ready_part1.html.erb
<h1>Begin Task - Part 1</h1>

<p>Good, you have done the trial.</p>
<p>You will now begin the task.</p>

<div class="buttons">
  <%= link_to "Begin task", show_part1_path, class: "btn btn-large btn-primary" %>
</div>

app/views/pages/ready_part2.html.erb
<h1>Begin Task - Part 2</h1>

<p>You will now begin the task.</p>

<div class="buttons">
  <%= link_to "Begin task", show_part2_path, class: "btn btn-large btn-primary" %>
</div>

app/views/pages/signedin.html.erb
<%= provide(:id, request.session_options[:id]) %>

<p>You're already signed in as a user. <a href="/show">Click here to continue the test.</a> Or <%= link_to 'click here to sign out and redo the test.', session_path(:id => request.session_options[:id]), :method => :delete %></p>

app/views/pages/totraining.html.erb
<h1>Example Images</h1>

<p>Before you begin the test, you will see some examples on how to rate quality and beauty of images.</p>

<div class="buttons">
  <%= link_to "Go to training", training_path, class: "btn btn-large btn-primary" %> 
</div>

app/views/pages/trainaest.html.erb
<h1>Example : Image Aesthetic Appeal</h1> 
<!--<%= session[:test_set] %>
<%= session[:subtask] %>
<%= session[:first] %>-->

<p>
We also ask you to rate how beautiful you think an image is (the image's aesthetic appeal). You may think that an image is still beautiful even if the quality is not excellent.
</p>
<br>

<div id="test_image">
	<%= link_to image_tag('train-1.jpg'), '#' %>
</div>

<p>
Please indicate the image's level of <b>beauty</b> below:
</p>

<div id="slider-ACR-Rec"></div>
<table style="width:100%">
	<tr>
		<td style="text-align:left" width="12.5%">Bad</td>
		<td style="text-align:center" >Poor</td>
		<td style="text-align:center" width="25%">Fair</td>
		<td style="text-align:center" width="25%">Good</td>
		<td style="text-align:right" width="12.5%">Excellent</td>
	</tr>
</table>
<br>
<br>

<div class="buttons">
  <%= link_to "Next", ready_path, class: "btn btn-large btn-primary" %> 
</div>

app/views/pages/trainend.html.erb
<h1>Example : Image Aesthetic Appeal</h1> 
<!--<%= session[:test_set] %>
<%= session[:subtask] %>
<%= session[:first] %>-->

<div id="test_image">
	<%= link_to image_tag('like_5.jpg'), '#' %>
</div>

<p>
Please indicate the image's level of beauty below:
</p>

<div id="slider-ACR-Rec"></div>
<table style="width:100%">
	<tr>
		<td style="text-align:left" width="12.5%">Bad</td>
		<td style="text-align:center" >Poor</td>
		<td style="text-align:center" width="25%">Fair</td>
		<td style="text-align:center" width="25%">Good</td>
		<td style="text-align:right" width="12.5%">Excellent</td>
	</tr>
</table>
<br>
<br>

<div class="buttons">
  <%= link_to "Next", ready_path, class: "btn btn-large btn-primary" %> 
</div>

app/views/pages/training.html.erb
<h1>Example : Image Quality</h1> 
<!--<%= session[:test_set] %>
<%= session[:subtask] %>
<%= session[:first] %>-->

<p>
In this experiment, a low quality image is distorted by blocks. Below is an example of a <b>bad</b> quality image. 
</p>
<br>

<div id="test_image">
	<%= link_to image_tag('WomanHatLow.bmp'), '#' %>
</div>


<p>
Please indicate the image's level of <b>quality</b> below:
</p>

<div id="slider-ACR-Rec"></div>
<table style="width:100%">
	<tr>
		<td style="text-align:left" width="12.5%">Bad</td>
		<td style="text-align:center" >Poor</td>
		<td style="text-align:center" width="25%">Fair</td>
		<td style="text-align:center" width="25%">Good</td>
		<td style="text-align:right" width="12.5%">Excellent</td>
	</tr>

</table>
<br>
<br>

<div class="buttons">
  <%= link_to "Next", trainreco_path, class: "btn btn-large btn-primary" %> 
</div>