config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index', campaign: nil, userid: nil, mw: nil
  get 'pages/index/:user/:mw' => 'pages#index', user: :user, mw: :mw
  post 'crowdsourceuser' => 'users#crowdsourceuser'
  get 'newuser' => 'users#new'
  post 'newuser' => 'users#create'
  get 'about' => 'pages#about'

  get 'intro_part1' => 'pages#intro_part1'
  get 'totraining_part1' => 'pages#totraining_part1'
  get 'training_part1' => 'pages#training_part1'
  get 'golden' => 'pages#golden'
  get 'submit_golden' => 'pages#submit_golden'

  get 'ready_part1' => 'pages#ready_part1'
  get 'show_part1' => 'scores#show_part1'
  get 'checkimage_part1' => 'scores#checkimage_part1'
  get 'contentcheck_part1' => 'scores#contentcheck_part1'

  get 'intro_part2' => 'pages#intro_part2'
  get 'totraining_part2' => 'pages#totraining_part2'
  get 'training_part2' => 'pages#training_part2'

  get 'ready_part2' => 'pages#ready_part2'
  get 'show_part2' => 'scores#show_part2'
  get 'checkimage_part2' => 'scores#checkimage_part2'
  get 'contentcheck_part2' => 'scores#contentcheck_part2'

  post 'update' => 'users#update'
  get 'content' => 'users#content'
  get 'contentanswer' => 'users#contentanswer'

  get 'end' => 'pages#end'
  get 'endwrong' => 'pages#endwrong'
  get 'logout' => 'pages#logout'

  resources :scores

  resources :users

  resources :campaignsets

  resources :images

end

app/views/layouts/_footer.html.erb
<footer class="footer"> 
  <nav> 
    <ul>
    <% if request.path != "/newuser" && request.path != "" %>
      <li>User: <%= session[:user]%> (<%= link_to "Logout", logout_path %>)</li>
    <% end %>
      <li> | </li>
      <li> <%= link_to "About",   about_path %> </li>
    </ul> 
  </nav> 
  <small>
  <%= link_to image_tag("tu.jpg"), 'http://tudelft.nl/' %>
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="header">

<% if request.path != "/newuser" && request.path != "" %>
    <% if !session[:userid]%>
        <% controller.redirect_to newuser_path %>
     <% end %>
<% end %>

</div>

app/views/layouts/_question.html.erb
<div id="start_time"></div>

<div id = "q1">
    <hr>
    <p>
    Would you <b>like to visit</b> this place?
    </p>

    <div id="slider-Attractiveness"></div>
    <table style="width:100%">
        <tr>
            <td style="text-align:left" width="12.5%">Extremely unlikely</td>
            <td style="text-align:center" >Unlikely</td>
            <td style="text-align:center" width="25%">Neutral</td>
            <td style="text-align:center" width="25%">Likely</td>
            <td style="text-align:right" width="12.5%">Extremely likely</td>
        </tr>
    </table>
</div>

<div id="q2" hidden>
    <hr>
    <p>
    Are you <b>familiar</b> with this place?
      <label class="btn btn-default"><input type="radio" name="familiarity" value="yes">Yes</label>
      <label class="btn btn-default"><input type="radio" name="familiarity" value="no">No</label>
    </p>
</div>

<div id = "q3" hidden>
    <hr>
    <p>
    How <b>unique</b> is this place?
    </p>

    <div id="slider-Uniqueness"></div>
    <table style="width:100%">
        <tr>
            <td style="text-align:left" width="12.5%">I frequently see something like this</td>
            <td style="text-align:center" >Ordinary</td>
            <td style="text-align:center" width="25%">Neutral</td>
            <td style="text-align:center" width="25%">Unique</td>
            <td style="text-align:right" width="12.5%">I've never seen anything like this</td>
        </tr>
    </table>
</div>

<div id="q4" hidden>
    <hr>
    <p>
    Do you consider this place <b>friendly</b>?
        <label class="btn btn-default"><input type="radio" name="friendliness" value="yes">Yes</label>
        <label class="btn btn-default"><input type="radio" name="friendliness" value="no">No</label>
    </p>
</div>

<div id="q5" hidden>
    <hr>
    <p>
    How does this place make you <b>feel</b>?
    </p>
    <div class="offset4">
        <div id="affectchanger_div" hidden><input type="button" id="affectchanger" style="width:100px" class="btn btn-default" value="Change"></div>
        <canvas id="affect" width="100px" height="100px" style="border:0; padding:0;">
        </canvas>
    </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]> 
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script> 
  <![endif]--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %> | Urban Attractiveness Evaluation Survey</title>

<%= javascript_include_tag "external/firebase" %>

  <%= stylesheet_link_tag "custom", :media => "all"%>
  <%= stylesheet_link_tag "bootstrap/bootstrap", :media => "all" %>
  <%= stylesheet_link_tag "jquery-ui.min", :media => "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap/bootstrap" %>
  <%= javascript_include_tag "external/jquery/jquery" %>
  <%= javascript_include_tag "jquery-ui.min" %>
  <%= javascript_include_tag "scales" %>
  <%= javascript_include_tag "buttons" %>

    <%= javascript_include_tag "external/jquery/jquery.mobile-1.1.0.min" %>
    <%= javascript_include_tag "external/jquery/jquery.ui.affectbutton" %>
    <%= javascript_include_tag "external/jquery/jquery.ui.affectbutton.mobile" %>


  <%= render 'layouts/shim' %> 
</head>
<body>
	<%= render 'layouts/header' %> 
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
		
	</div>
</body>
</html>